import { Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Pencil, ReceiptText, Search, Trash2, UserRound, Wallet } from "lucide-react";
import { demoCustomers, readDemoAdmin, type DemoAdminState, type DemoCustomer } from "../../lib/xoxo-demo";
import { formatKzt } from "../../lib/formatters/money";
import { BottomSheet } from "../shared/BottomSheet";

const initial: DemoAdminState = { drinks: [], orders: [] };
const guestsKey = "xoxo:command-center:guests:v1";

export function GuestsScreen() {
  const [data, setData] = useState(initial);
  const [guests, setGuests] = useState<DemoCustomer[]>(demoCustomers);
  const [query, setQuery] = useState("");
  const [view, setView] = useState<"guests" | "orders">("guests");
  const [editing, setEditing] = useState<DemoCustomer | null>(null);
  const [draft, setDraft] = useState({ name: "", phone: "" });
  useEffect(() => { setData(readDemoAdmin()); try { const saved = localStorage.getItem(guestsKey); if (saved) setGuests(JSON.parse(saved) as DemoCustomer[]); } catch { /* Use demo guests. */ } }, []);
  const saveGuests = (next: DemoCustomer[]) => { setGuests(next); try { localStorage.setItem(guestsKey, JSON.stringify(next)); } catch { /* Session changes still work. */ } };
  const clients = useMemo(() => guests.filter((client) => client.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()) || client.phone.includes(query)), [guests, query]);
  const orders = useMemo(() => data.orders.filter((order) => { const client = guests.find((item) => item.id === order.customerId); return `${client?.name ?? ""} ${order.items}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()); }), [data.orders, guests, query]);
  const openEdit = (guest: DemoCustomer) => { setEditing(guest); setDraft({ name: guest.name, phone: guest.phone }); };
  const saveGuest = () => { if (!editing || !draft.name.trim() || !draft.phone.trim()) return; saveGuests(guests.map((guest) => guest.id === editing.id ? { ...guest, name: draft.name.trim(), phone: draft.phone.trim() } : guest)); setEditing(null); };
  const deleteGuest = (guest: DemoCustomer) => { if (!window.confirm(`Удалить гостя «${guest.name}»?`)) return; saveGuests(guests.filter((item) => item.id !== guest.id)); };
  return <div className="space-y-5 px-4 pb-32 pt-6">
    <header><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-700">XOXO · гости</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Клиенты и чеки</h1><p className="mt-1 text-sm text-slate-500">История гостя и демо-заказов</p></header>
    <section className="grid grid-cols-2 gap-2"><div className="rounded-3xl bg-[#12332b] p-4 text-white"><UserRound size={18} className="text-amber-300"/><p className="mt-4 text-2xl font-bold">{guests.length}</p><p className="text-xs text-white/65">гостей</p></div><div className="rounded-3xl bg-[#12332b] p-4 text-white"><ReceiptText size={18} className="text-amber-300"/><p className="mt-4 text-2xl font-bold">{data.orders.length}</p><p className="text-xs text-white/65">чеков</p></div></section>
    <Link to="/" search={{ reservations: true }} className="flex min-h-16 items-center gap-3 rounded-3xl bg-white p-4 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><CalendarDays size={20}/></span><span className="flex-1"><strong className="block">Брони и столы</strong><span className="text-xs text-slate-500">Открыть зал с реальными бронями</span></span><span aria-hidden>→</span></Link>
    <div className="flex rounded-2xl bg-white p-1 shadow-sm"><button type="button" onClick={() => setView("guests")} className={`min-h-11 flex-1 rounded-xl text-sm font-bold ${view === "guests" ? "bg-[#12332b] text-white" : "text-slate-500"}`}>Гости</button><button type="button" onClick={() => setView("orders")} className={`min-h-11 flex-1 rounded-xl text-sm font-bold ${view === "orders" ? "bg-[#12332b] text-white" : "text-slate-500"}`}>Заказы</button></div>
    <label className="flex h-12 items-center gap-2 rounded-2xl bg-white px-3 shadow-sm"><Search size={18} className="text-slate-400"/><input className="w-full bg-transparent text-sm outline-none" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Поиск гостя или заказа"/></label>
    {view === "guests" ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{clients.map((client) => { const clientOrders = data.orders.filter((order) => order.customerId === client.id); const cashback = clientOrders.reduce((sum, order) => sum + order.cashback, 0); return <article key={client.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 font-bold text-emerald-800">{client.name.slice(0,1)}</span><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{client.name}</h2><p className="text-xs text-slate-500">{client.phone}</p></div><div className="flex gap-1"><button type="button" onClick={() => openEdit(client)} className="rounded-xl bg-slate-100 p-2 text-slate-600" aria-label={`Редактировать ${client.name}`}><Pencil size={15}/></button><button type="button" onClick={() => deleteGuest(client)} className="rounded-xl bg-rose-50 p-2 text-rose-700" aria-label={`Удалить ${client.name}`}><Trash2 size={15}/></button></div></div><div className="mt-4 flex justify-between border-t border-slate-100 pt-3 text-sm"><span>{clientOrders.length} заказа</span><span className="flex items-center gap-1 font-semibold text-emerald-700"><Wallet size={14}/> {formatKzt(cashback)}</span></div><div className="mt-3 space-y-1">{clientOrders.slice(0, 2).map((order) => <p key={order.id} className="truncate text-xs text-slate-500">{new Date(order.date).toLocaleDateString("ru-RU")} · {order.items}</p>)}</div></article>; })}</div> : <div className="space-y-2">{orders.map((order) => <article key={order.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-bold">{guests.find((client) => client.id === order.customerId)?.name ?? "Гость"}</p><p className="mt-1 text-xs text-slate-500">{new Date(order.date).toLocaleDateString("ru-RU")} · {order.items}</p></div><div className="shrink-0 text-right"><p className="font-bold">{formatKzt(order.total)}</p>{order.cashback > 0 && <p className="mt-1 text-xs font-semibold text-emerald-700">+{formatKzt(order.cashback)} кэшбэк</p>}</div></div></article>)}</div>}
    {editing && <BottomSheet eyebrow="Карточка гостя" title="Редактировать гостя" onClose={() => setEditing(null)}><div className="space-y-3 pb-2"><input className="field" value={draft.name} onChange={(event) => setDraft((value) => ({ ...value, name: event.target.value }))} placeholder="Имя"/><input className="field" value={draft.phone} onChange={(event) => setDraft((value) => ({ ...value, phone: event.target.value }))} placeholder="Телефон" inputMode="tel"/><button type="button" onClick={saveGuest} className="w-full rounded-2xl bg-[#12332b] py-4 font-semibold text-white">Сохранить изменения</button></div></BottomSheet>}
  </div>;
}
